name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch: # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          # Ping the app and follow redirects
          STATUS=$(curl -L -o /dev/null -s -w "%{http_code}" https://ev-chatbot-demo1.streamlit.app/)
          echo "HTTP status code: $STATUS"

          # Check if the response is 200
          if [ $STATUS -eq 200 ]; then
            echo "✅ Streamlit app is alive!"
          else
            echo "❌ Streamlit app did not respond properly!"
            exit 1
          fi
