name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App and Log Status
        run: |
          URL="https://ev-chatbot-demo1.streamlit.app/"
          MAX_RETRIES=3
          RETRY_COUNT=0
          LOG_FILE="ping_log.txt"

          echo "Ping run at $(date)" >> $LOG_FILE

          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            STATUS=$(curl -L -k -o /dev/null -s -w "%{http_code}" $URL)
            echo "HTTP status code: $STATUS" >> $LOG_FILE

            if [ $STATUS -eq 200 ]; then
              echo "✅ Streamlit app is alive!" >> $LOG_FILE
              break
            else
              echo "❌ Streamlit app did not respond properly. Retry $((RETRY_COUNT+1))/$MAX_RETRIES..." >> $LOG_FILE
              RETRY_COUNT=$((RETRY_COUNT+1))
              sleep 10
            fi
          done

          if [ $STATUS -ne 200 ]; then
            echo "❌ Streamlit app failed after $MAX_RETRIES retries." >> $LOG_FILE
            exit 1
          fi

      - name: Upload ping log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ping-log
          path: ping_log.txt
